version: 0.2
phases:
    install:
        runtime-versions:
            docker: 18
    build:
        commands:
            - sudo yum install jq -y
            - ContainerName="todo"
            - printf '[{"name":"DemoAppContainer","imageUri":"593063176004.dkr.ecr.us-east-1.amazonaws.com/nginx:latest"}]' > imagedefinitions.json
            - sed -i -e "s|CONTAINER_NAME|$ContainerName|g" imagedefinitions.json
            - sed -i -e "s|IMAGE_URI|$ImageURI|g" imagedefinitions.json
            - cat imagedefinitions.json

artifacts:
    files:
        - imagedefinitions.json
